### ISSUE TITLE
Lipsync issue

### ISSUE THREAD

**Issue by tomasz-oponowicz** [castlabs/dashas#30]
With commit 90becf77bf8c121fc44b9b67589b70248a814658 lipsync issue has been introduced for certain stream.

**Comment by joanneball** [comment]
Hi
I have tried to get the audio and video to stay in sync and I can't.
I was using windows but installed a computer with ubuntu in case there was a problem with other encoders etc it still doesn't. It works perfectly in dash.js
i can't use your encrypter because it tries to create a root directory which is not allowed in windows 8 or linux
I have tried ffmpeg &MP4Box. I also tried with a sorenson squeeze encoder.

One of the mpd file I used was
http://pictaural.ie/mpeg-dash/Ubuntu/Hatz.mpd
Thanks
  Joanne
